# Generated by Django 4.2.1 on 2023-05-31 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledescription',
            name='title',
        ),
    ]
