# Generated by Django 4.2.2 on 2023-09-26 05:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0005_alter_profiledescription_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="name",
        ),
    ]
