# Generated by Django 4.2.2 on 2023-09-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0006_remove_profile_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="photo",
        ),
        migrations.AddField(
            model_name="profile",
            name="photo_url",
            field=models.URLField(blank=True),
        ),
    ]
