# Generated by Django 4.2.2 on 2023-09-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0008_alter_personaldata_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaldata",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
