# Generated by Django 4.2.2 on 2023-09-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0009_alter_personaldata_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactdata",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="contactdata",
            name="github",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="contactdata",
            name="linkedin",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="contactdata",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
