# Generated by Django 4.2.2 on 2023-09-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0011_alter_contactdata_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiledescription",
            name="summary",
            field=models.TextField(blank=True),
        ),
    ]
