# Generated by Django 4.2.2 on 2023-09-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0012_alter_profiledescription_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workexperience",
            name="company",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="company_description",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="position",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="skills",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
