# Generated by Django 4.2.2 on 2023-10-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0014_alter_educationinformation_degree_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="language",
            name="proficiency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("N", "Nativo"),
                    ("P", "Principiante"),
                    ("B", "Básico"),
                    ("I", "Intermedio"),
                    ("A", "Avanzado"),
                    ("F", "Fluente"),
                ],
                max_length=1,
            ),
        ),
    ]
