# Generated by Django 4.2.2 on 2023-10-06 19:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0015_alter_language_name_alter_language_proficiency"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactdata",
            old_name="profile",
            new_name="profile_id",
        ),
        migrations.RenameField(
            model_name="educationinformation",
            old_name="profile",
            new_name="profile_id",
        ),
        migrations.RenameField(
            model_name="language",
            old_name="profile",
            new_name="profile_id",
        ),
        migrations.RenameField(
            model_name="personaldata",
            old_name="profile",
            new_name="profile_id",
        ),
        migrations.RenameField(
            model_name="profiledescription",
            old_name="profile",
            new_name="profile_id",
        ),
        migrations.RenameField(
            model_name="workexperience",
            old_name="profile",
            new_name="profile_id",
        ),
    ]
