# Generated by Django 4.2.2 on 2023-10-07 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0016_rename_profile_contactdata_profile_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workexperience",
            old_name="description",
            new_name="Responsibility",
        ),
        migrations.RemoveField(
            model_name="workexperience",
            name="skills",
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_text", models.CharField(blank=True, max_length=25)),
                (
                    "work_experience_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="resume.workexperience",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("achievement_text", models.CharField(blank=True, max_length=80)),
                (
                    "work_experience_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="resume.workexperience",
                    ),
                ),
            ],
        ),
    ]
