# Generated by Django 4.2.2 on 2023-10-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0018_alter_skill_work_experience_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workexperience",
            old_name="Responsibility",
            new_name="responsibility",
        ),
        migrations.AddField(
            model_name="workexperience",
            name="skill",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
