# Generated by Django 4.2.2 on 2023-10-07 17:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0019_rename_responsibility_workexperience_responsibility_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workexperience",
            old_name="skill",
            new_name="skills",
        ),
    ]
